cloud:
  aws:
    credentials:
      access-key: AKIAXUMRFRARVGRPEVPN
      secret-key: 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
    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: prabhakarbucket1


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 9090
